FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

# Copy requirements file first to leverage Docker caching
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code and logging configuration
COPY app /app/
COPY templates /app/templates/
COPY static /app/static/

# Add a non-root user
RUN groupadd -r appuser && useradd --no-log-init -r -g appuser appuser

# Change ownership of the application files
RUN chown -R appuser:appuser /app

# Switch to the non-root user
USER appuser

# Embed build information
ARG BUILD_DATE
ARG BUILD_VERSION
ENV BUILD_INFO="Development version $BUILD_VERSION, not for release - $BUILD_DATE"

# Run the application
CMD ["python", "run.py"]
